apiVersion: v2
name: mailserver
description: A HELM chart for deploying a complete mailserver

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.1.0

dependencies:
- name: mariadb
  version: 10.5.3
  repository: https://raw.githubusercontent.com/technicalguru/helm-repo/master/repo
- name: postfix
  version: 1.1.0
  repository: https://raw.githubusercontent.com/technicalguru/helm-repo/master/repo
- name: amavis
  version: 1.0.0
  repository: https://raw.githubusercontent.com/technicalguru/helm-repo/master/repo
- name: opendkim
  version: 1.0.0
  repository: https://raw.githubusercontent.com/technicalguru/helm-repo/master/repo
- name: postfixadmin
  version: 1.0.0
  repository: https://raw.githubusercontent.com/technicalguru/helm-repo/master/repo
- name: roundcube
  version: 1.0.0
  repository: https://raw.githubusercontent.com/technicalguru/helm-repo/master/repo
