apiVersion: v1
kind: Service
metadata:
  name: {{ include "roundcube.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "roundcube.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "roundcube.selectorLabels" . | nindent 4 }}
