# Default values for amavis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

# $enabled - do not install anything (useful as dependency chart)
enabled: true

# $replicaCount - the number of replicas in the deployment to create
replicaCount: 1

# $image            - definition of docker image
# $image.name       - the image name
# $image.tag        - the image tag
# $image.pullPolicy - The pull policy for the image
image:
  name: technicalguru/mailserver-amavis
  tag: latest
  pullPolicy: IfNotPresent

# $additionalLabels - additional labels to attach to a pod
additionalLabels: {}
#  labelKey: labelValue

#####################
# Service settings
#####################
# $service.port - the incoming service port
service:
  port: 10024

# $resources - additional resource requirements
resources: {}

# $affinity.enabled   - whether node affinity shall be specified
# $affinity.nodeLabel - the key of the node label for affinity stickiness
# $affinity.nodeValues - the node label values the pod is running on (dev, uat, prod)
affinity:
  enabled: true
  nodeLabel: "mailserver/environment"
  nodeValues: 
  - "dev"

#####################
# Mail settings
#####################
# $defaultDomain     - default mail domain
# $relayHostname     - name of host for Amavis mail scanning (optional)
# $relayPort         - relay port for Amavis mail scanning
# $virusAdminEmail   - e-mail of admin to be informed when viruses were quarantined
defaultDomain: ""
relayHostname: "postfix-internal"
relayPort: "10025"
virusAdminEmail: ""
notifySenderEmail: ""
notifyAdminEmail: ""

###############################
# VolumeClaims to mount
###############################
volumeClaims:
  virusmails: "amavis-virusmails"

###############################
# SecurityContext on pod level
###############################
securityContext: {}

###########################
# Additional customization 
###########################
# $configfiles - list of config file definitions
# $configfiles[].name - unique name for config definition
# $configfiles[].mountPath - path of file in pod to mount at
# $configfiles[].content - the config file content
# ATTENTION: You better pass the content with command line arguments to HELM:
#       --set-file "configFiles[0].content=/path/to/file" (quotes required)
configFiles: []
#- name: example1
#  mountPath: /etc/spamassassin/x10-example.cf
#  content: "content of file"
#- name: example2
#  mountPath: /etc/spamassassin/x20-example.cf
#  content: "content of file"

# $additionalTemplateSpec  - Add more deployment template specification at this value
# $additionalPodSpec       - Add more pod specification at this value
# $additionalContainerSpec - Add more container specification at this value
additionalTemplateSpec: {}
additionalPodSpec: {}
additionalContainerSpec: {}

