# Default values for opendkim.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

# $replicaCount - the number of replicas in the deployment to create
replicaCount: 1

# $image            - definition of docker image
# $image.repository - the image name (without tag)
# $image.pullPolicy - The pull policy for the image
image:
  repository: technicalguru/mailserver-dkim
  pullPolicy: IfNotPresent

# $additionalLabels - additional labels to attach to a pod
additionalLabels: {}
#  labelKey: labelValue

#####################
# Service settings
#####################
# $service.port - the incoming service port
service:
  port: "41001"
  http: "80"

# $resources - additional resource requirements
resources: {}

# $affinityLabel - the key of the node label for affinity stickiness
# $environment   - the node label the pod is running on (dev, uat, prod)
affinityLabel: "mailserver/environment"
environment: "dev"

#####################
# Mail settings
#####################
# $defaultDomain     - default mail domain
defaultDomain: ""

#####################
# Database settings
#####################
# $dbHostname - the database host
# $dbName     - the database instance name
# $dbUser     - the database user to use
# $dbPassword - the password of the database user to use
# $dbSetupPassword - the root password for setup
dbHostname: "mariadb"
dbName: "opendkim"
dbUser: "opendkim"
dbPassword: "opendkim"
dbSetupPassword: "password"

###########################
# Additional customization 
###########################
# $additionalTemplateSpec  - Add more deployment template specification at this value
# $additionalPodSpec       - Add more pod specification at this value
# $additionalContainerSpec - Add more container specification at this value
additionalTemplateSpec: {}
additionalPodSpec: {}
additionalContainerSpec: {}

