# Default values for opendkim.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

# $enabled - do not install anything (useful as dependency chart)
enabled: true

# $replicaCount - the number of replicas in the deployment to create
replicaCount: 1

# $image            - definition of docker image
# $image.name       - the image name
# $image.tag        - the image tag
# $image.pullPolicy - The pull policy for the image
image:
  name: technicalguru/mailserver-opendkim
  tag: latest
  pullPolicy: IfNotPresent

# $additionalLabels - additional labels to attach to a pod
additionalLabels: {}
#  labelKey: labelValue

#####################
# Service settings
#####################
# $service.port - the incoming service port
# $service.http - the HTTP port (not in use yet)
service:
  port: "41001"
  http: "80"

# $resources - additional resource requirements
resources: {}

# $affinity.enabled   - whether node affinity shall be specified
# $affinity.nodeLabel - the key of the node label for affinity stickiness
# $affinity.nodeValues - the node label values the pod is running on (dev, uat, prod)
affinity:
  enabled: true
  nodeLabel: "mailserver/environment"
  nodeValues: 
  - "dev"

#####################
# Mail settings
#####################
# $defaultDomain     - default mail domain
defaultDomain: ""

#####################
# Database settings
#####################
# $dbHostname - the database host
# $dbName     - the database instance name
# $dbSecret   - Kubernetes secret to be used for retrieving passwords
#   $name             - Name of Kubernetes secret (set empty when using direct values)
#   $usernameKey      - key in secret that holds the database username
#   $passwordKey      - key in secret that holds the password of the database user
#   $setupPasswordKey - key in secret that holds the root password for setup
# $dbUser     - the database user to use (when not using secret)
# $dbPassword - the password of the database user to use (when not using secret)
# $dbSetupPassword - the root password for setup (when not using secret)
dbHostname: "mariadb"
dbName: "opendkim"
dbSecret:
  name: ""
  usernameKey: username
  passwordKey: password
  setupPasswordKey: setupPassword
dbUser: "opendkim"
dbPassword: "opendkim"
dbSetupPassword: "password"

###########################
# Additional customization 
###########################
# $additionalTemplateSpec  - Add more deployment template specification at this value
# $additionalPodSpec       - Add more pod specification at this value
# $additionalContainerSpec - Add more container specification at this value
additionalTemplateSpec: {}
additionalPodSpec: {}
additionalContainerSpec: {}

