apiVersion: v1
kind: Service
metadata:
  name: {{ include "opendkim.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opendkim.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: opendkim
      port: {{ .Values.service.port }}
      targetPort: opendkim
      protocol: TCP
    - name: http
      port: {{ .Values.service.http }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "opendkim.selectorLabels" . | nindent 4 }}
