apiVersion: v1
kind: Service
metadata:
  name: {{ include "postfixadmin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postfixadmin.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "postfixadmin.selectorLabels" . | nindent 4 }}
