apiVersion: v2
name: postfixadmin
description: A HELM chart for deploying PostfixAdmin

type: application

# Chart version does not reflect the app version
version: 1.0.0

# PostfixAdmin version
appVersion: 3.2.4.0

