# Default values for postfixadmin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

# $replicaCount - the number of replicas in the deployment to create
replicaCount: 1

# $image            - definition of docker image
# $image.repository - the image name (without tag)
# $image.pullPolicy - The pull policy for the image
image:
  repository: technicalguru/mailserver-postfixadmin
  pullPolicy: IfNotPresent

# $additionalLabels - additional labels to attach to a pod
additionalLabels: {}
#  labelKey: labelValue

#####################
# Service settings
#####################
# $service.port - Webserver port to bind the service to
service:
  port: 80

# $resources - additional resource requirements
resources: {}

#####################
# Database settings
#####################
# $dbHostname    - the database host
# $dbName        - the database instance name
# $dbUser        - the database user to use
# $dbPassword    - the password of the database user to use
dbHostname: "mariadb"
dbName: "mail"
dbUser: "postfix"
dbPassword: "postfix"


########################
# PostfixAdmin settings
########################
# $mailserverHostname - hostname to be used for HELO greeting
# $mailserverPort     - relay port for Amavis mail scanning
# $setupPassword      - the setup password for PostfixAdmin
# $abuseEmail         - e-mail of abuse admin
# $hostmasterEmail    - e-mail of host responsible
# $postmasterEmail    - e-mail of mail responsible
# $webmasterEmail     - e-mail of web responsible
mailserverHostname: "postfix"
mailserverPort: "25"
setupPassword: "password"
abuseEmail: "abuse@localhost"
hostmasterEmail: "hostmaster@localhost"
postmasterEmail: "postmaster@localhost"
webmasterEmail: "webmaster@localhost"

################################################
# More customization
################################################
# $additionalTemplateSpec  - Add more deployment template specification at this value
# $additionalPodSpec       - Add more pod specification at this value
# $additionalContainerSpec - Add more container specification at this value
additionalTemplateSpec: {}
additionalPodSpec: {}
additionalContainerSpec: {}
