# Default values for roundcube.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

# $enabled - do not install anything (useful as dependency chart)
enabled: true

# $replicaCount - the number of replicas in the deployment to create
replicaCount: 1

# $image            - definition of docker image
# $image.name       - the image name
# $image.tag        - the image tag
# $image.pullPolicy - The pull policy for the image
image:
  name: technicalguru/mailserver-roundcube
  tag: latest
  pullPolicy: IfNotPresent

# $additionalLabels - additional labels to attach to a pod
additionalLabels: {}
#  labelKey: labelValue

#####################
# Service settings
#####################
# $service.port - Webserver port to bind the service to
service:
  port: 80

# $resources - additional resource requirements
resources: {}

#####################
# Database settings
#####################
# $dbHostname - the database host
# $dbName     - the database instance name
# $dbSecret   - Kubernetes secret to be used for retrieving passwords
#   $name             - Name of Kubernetes secret (set empty when using direct values)
#   $usernameKey      - key in secret that holds the database username
#   $passwordKey      - key in secret that holds the password of the database user
# $dbUser     - the database user to use (when not using secret)
# $dbPassword - the password of the database user to use (when not using secret)
dbHostname: "mariadb"
dbName: "roundcube"
dbSecret:
  name: ""
  usernameKey: username
  passwordKey: password
dbUser: "roundcube"
dbPassword: "roundcube"


########################
# Roundcube settings
########################
# $imapServerHostname - hostname to be used for HELO greeting
# $smtpServerHostname - hostname to be used for HELO greeting
# $defaultDomain      - The default domain for login users
# $desSecret          - Kubernetes secret to be used for retrieving the DES key
#   $name                - Name of Kubernetes secret (set empty when using direct values)
#   $key                 - key in secret that holds the DES key
# $desKey             - a unique 24-char string for your server (when not using secret)
imapServerHostname: "postfix"
smtpServerHostname: "postfix"
defaultDomain: "localdomain"
desSecret:
  name: ""
  key: desKey
desKey: ""

###################################
# More customization
###################################
# $additionalTemplateSpec  - Add more deployment template specification at this value
# $additionalPodSpec       - Add more pod specification at this value
# $additionalContainerSpec - Add more container specification at this value
additionalTemplateSpec: {}
additionalPodSpec: {}
additionalContainerSpec: {}
