apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mariadb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "mariadb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mariadb.selectorLabels" . | nindent 8 }}
        {{- if .Values.additionalLabels -}}
          {{- toYaml .Values.additionalLabels | nindent 8 }}
        {{- end }}
    {{- if .Values.additionalTemplateSpec -}}
      {{- toYaml .Values.additionalTemplateSpec | nindent 4 }}
    {{- end }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.affinityLabel }}
                operator: In
                values:
                - {{ .Values.environment }}
      {{- if .Values.additionalPodSpec -}}
        {{- toYaml .Values.additionalPodSpec | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "{{ .Values.rootPassword }}"
        ports:
          - name: mysql
            containerPort: 3306
            protocol: TCP
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: configurations
          mountPath: /etc/mysql/conf.d/{{ include "mariadb.fullname" .}}-auth.cnf
          subPath: {{ include "mariadb.fullname" .}}-auth.cnf
        - name: configurations
          mountPath: /etc/mysql/conf.d/{{ include "mariadb.fullname" .}}-sizing.cnf
          subPath: {{ include "mariadb.fullname" .}}-sizing.cnf
        {{- if .Values.enableAuditLog }}
        - name: configurations
          mountPath: /etc/mysql/conf.d/{{ include "mariadb.fullname" .}}-audit-log.cnf
          subPath: {{ include "mariadb.fullname" .}}-audit-log.cnf
        {{- end }}
        {{- if .Values.additionalContainerSpec -}}
          {{- toYaml .Values.additionalContainerSpec | nindent 8 }}
        {{- end }}
      volumes:
      - name: data
        {{- if eq .Values.volumeType "hostPath" }}
        hostPath:
          path: /var/docker/{{ .Release.Name }}/{{ .Values.environment }}/mariadb/data
		{{- end }}
        {{- if eq .Values.volumeType "pvc" }}
        persistentVolumeClaim:
          claimName: {{ template "mariadb.fullname" . }}-storage
		{{- end }}
      - name: configurations
        configMap:
          name: {{ template "mariadb.fullname" . }}-configuration

