{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: mysql
      protocol: TCP
  selector:
    {{- include "mariadb.selectorLabels" . | nindent 4 }}
{{- end }}
